/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "interface-surface-page": 'var(--color-interface-surface-page)',
        "interface-surface-component": 'var(--color-interface-surface-component)',
		    white: 'var(--color-white)',
        "gray-200": 'var(--color-gray-200)',
        "gray-800": 'var(--color-gray-800)',
        "primary-700": 'var(--color-primary-700)',
        "interface-text-subtitle": 'var(--color-interface-text-subtitle)',
        "brand-support-1-400": 'var(--color-brand-support-1-400)',
        "interface-text-title": 'var(--color-interface-text-title)',
        "brand-highlight-600": 'var(--color-brand-highlight-600)',
        "brand-highlight-500": 'var(--color-brand-highlight-500)',
        tan: {
          "100": 'var(--color-tan-100)',
          "200": 'var(--color-tan-200)',
        },
        "brand-primary-pure": 'var(--color-brand-primary-pure)',
        steelblue: {
          "100": 'var(--color-steelblue-100)',
          "200": 'var(--color-steelblue-200)',
        },
        lightslategray: 'var(--color-lightslategray)',
        lightsteelblue: 'var(--color-lightsteelblue)',
        darkslategray: {
          "100": 'var(--color-darkslategray-100)',
          "200": 'var(--color-darkslategray-200)',
          "300": 'var(--color-darkslategray-300)',
        },
        "brand-highlight-300": 'var(--color-brand-highlight-300)',
        "brand-highlight-400": 'var(--color-brand-highlight-400)',
		    "brand-primary-600": 'var(--color-brand-primary-600)',
        "brand-primary-700": 'var(--color-brand-primary-700)',
		    "brand-primary-800": 'var(--color-brand-primary-800)',
        "tertiary-text-light": 'var(--color-tertiary-text-light)',
        "interface-stroke-default": 'var(--color-interface-stroke-default)',
		    "interface-stroke-soft": 'var(--color-interface-stroke-soft)',
        peachpuff: 'var(--color-peachpuff)',
        "teal-600": 'var(--color-teal-600)',
        "brand-support-1-pure": 'var(--color-brand-support-1-pure)',
        "body-text": 'var(--color-body-text)',
        "charts-color-0": 'var(--color-charts-color-0)',
        "secondary-text": 'var(--color-secondary-text)',
        "gray-600": 'var(--color-gray-600)',
        "gray-400": 'var(--color-gray-400)',
        "neutral-50": 'var(--color-neutral-50)',
        "interface-surface-component-muted": 'var(--color-interface-surface-component-muted)',
        "color-gray-text-teritiary": 'var(--color-color-gray-text-teritiary)',
        "light-theme-text-default": 'var(--color-light-theme-text-default)',
        "social-dribbble": 'var(--color-social-dribbble)',
        "light-theme-text-title": 'var(--color-light-theme-text-title)',
        "light-theme-text-subtitle": 'var(--color-light-theme-text-subtitle)',
        gold: 'var(--color-gold)',
        darkslateblue: 'var(--color-darkslateblue)',
        "neutral-200": 'var(--color-neutral-200)',
        "color-warning-tint100": 'var(--color-color-warning-tint100)',
        "color-warning-tint400": 'var(--color-color-warning-tint400)',
        gray: {
          "100": 'var(--color-gray-100)',
          "200": 'var(--color-gray-200)',
          "300": 'var(--color-gray-300)',
          "400": 'var(--color-gray-400)',
        },
        "interface-text-default": 'var(--color-interface-text-default)',
        gainsboro: 'var(--color-gainsboro)',
        "text-menu": 'var(--color-text-menu)',
        text: 'var(--color-text)',
        "light-theme-border-default": 'var(--color-light-theme-border-default)',
        "alert-red": 'var(--color-alert-red)',
        "red-600": 'var(--color-red-600)',
        snow: 'var(--color-snow)',
        "contrast-20-light": 'var(--color-contrast-20-light)',
        "tertiary-text-light1": 'var(--color-tertiary-text-light1)',
        "stroke-default": 'var(--color-stroke-default)',
        "gray-50": 'var(--color-gray-50)',
        "colors-highlight-pure": 'var(--color-colors-highlight-pure)',
        "colors-primary-pure": 'var(--color-colors-primary-pure)',
        "yellow-300": 'var(--color-yellow-300)',
        "color-secondary-base": 'var(--color-color-secondary-base)',
		    "interface-text-subtitle1": 'var(--color-interface-text-subtitle1)',
        "interface-text-default": 'var(--color-interface-text-default)',
        border: 'var(--color-border)',
        "neutral-sig-sand-1": 'var(--color-neutral-sig-sand-1)',
      },
      spacing: {
        boundvariablesdata: "16px",
        boundvariablesdata2: "8px",
        boundvariablesdata3: "12px",
        boundvariablesdata4: "4px",
        boundvariablesdata5: "10px",
        boundvariablesdata6: "20px",
        boundvariablesdata7: "32px",
        "spacing-1": "4px",
        boundvariablesdata8: "24px",
        "spacing-5": "20px",
        "spacing-4": "16px",
        boundvariablesdata9: "2px",
      },
      fontFamily: {
        "text-xs-font-normal": "Inter",
        "sig-12": "'Work Sans'",
        poppins: "Poppins",
        kanit: "Kanit",
      },
      borderRadius: {
        "12xs": "1px",
        "4xs": "9px",
        "9980xl": "9999px",
        "8xs": "5px",
        "81xl": "100px",
        "3xs": "10px",
        "rounded-lg": "8px",
        "rounded-full": "9999px",
        "border-radius-rounded-full": "9999px",
        "spacing-05": "2px",
        "rounded-3xl": "24px",
        "rounded-md": "6px",
      },
    },
    fontSize: {
      sm: "14px",
      "3xs": "10px",
      xs: "12px",
      "13xl": "32px",
      base: "16px",
      lg: "18px",
      "4xs": "9px",
      "17xl": "36px",
      "5xl": "24px",
      xl: "20px",
      "21xl": "40px",
      "2xs": "11px",
      inherit: "inherit",
    },
  },
  corePlugins: {
    preflight: false,
  },
};
